// Generated by gencpp from file neural_network_msgs/NeuralNetworkDetection.msg
// DO NOT EDIT!


#ifndef NEURAL_NETWORK_MSGS_MESSAGE_NEURALNETWORKDETECTION_H
#define NEURAL_NETWORK_MSGS_MESSAGE_NEURALNETWORKDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace neural_network_msgs
{
template <class ContainerAllocator>
struct NeuralNetworkDetection_
{
  typedef NeuralNetworkDetection_<ContainerAllocator> Type;

  NeuralNetworkDetection_()
    : header()
    , object_class(0)
    , detection_score(0.0)
    , xmin(0)
    , xmax(0)
    , ymin(0)
    , ymax(0)
    , variance_xmin(0.0)
    , variance_xmax(0.0)
    , variance_ymin(0.0)
    , variance_ymax(0.0)  {
    }
  NeuralNetworkDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_class(0)
    , detection_score(0.0)
    , xmin(0)
    , xmax(0)
    , ymin(0)
    , ymax(0)
    , variance_xmin(0.0)
    , variance_xmax(0.0)
    , variance_ymin(0.0)
    , variance_ymax(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _object_class_type;
  _object_class_type object_class;

   typedef float _detection_score_type;
  _detection_score_type detection_score;

   typedef int16_t _xmin_type;
  _xmin_type xmin;

   typedef int16_t _xmax_type;
  _xmax_type xmax;

   typedef int16_t _ymin_type;
  _ymin_type ymin;

   typedef int16_t _ymax_type;
  _ymax_type ymax;

   typedef float _variance_xmin_type;
  _variance_xmin_type variance_xmin;

   typedef float _variance_xmax_type;
  _variance_xmax_type variance_xmax;

   typedef float _variance_ymin_type;
  _variance_ymin_type variance_ymin;

   typedef float _variance_ymax_type;
  _variance_ymax_type variance_ymax;





  typedef boost::shared_ptr< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> const> ConstPtr;

}; // struct NeuralNetworkDetection_

typedef ::neural_network_msgs::NeuralNetworkDetection_<std::allocator<void> > NeuralNetworkDetection;

typedef boost::shared_ptr< ::neural_network_msgs::NeuralNetworkDetection > NeuralNetworkDetectionPtr;
typedef boost::shared_ptr< ::neural_network_msgs::NeuralNetworkDetection const> NeuralNetworkDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator1> & lhs, const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_class == rhs.object_class &&
    lhs.detection_score == rhs.detection_score &&
    lhs.xmin == rhs.xmin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymin == rhs.ymin &&
    lhs.ymax == rhs.ymax &&
    lhs.variance_xmin == rhs.variance_xmin &&
    lhs.variance_xmax == rhs.variance_xmax &&
    lhs.variance_ymin == rhs.variance_ymin &&
    lhs.variance_ymax == rhs.variance_ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator1> & lhs, const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neural_network_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32bfad3528ed00c65e8e80188ba162ac";
  }

  static const char* value(const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32bfad3528ed00c6ULL;
  static const uint64_t static_value2 = 0x5e8e80188ba162acULL;
};

template<class ContainerAllocator>
struct DataType< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neural_network_msgs/NeuralNetworkDetection";
  }

  static const char* value(const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int16 object_class\n"
"float32 detection_score\n"
"\n"
"int16 xmin\n"
"int16 xmax\n"
"int16 ymin\n"
"int16 ymax\n"
"\n"
"float32 variance_xmin\n"
"float32 variance_xmax\n"
"float32 variance_ymin\n"
"float32 variance_ymax\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_class);
      stream.next(m.detection_score);
      stream.next(m.xmin);
      stream.next(m.xmax);
      stream.next(m.ymin);
      stream.next(m.ymax);
      stream.next(m.variance_xmin);
      stream.next(m.variance_xmax);
      stream.next(m.variance_ymin);
      stream.next(m.variance_ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeuralNetworkDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neural_network_msgs::NeuralNetworkDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_class: ";
    Printer<int16_t>::stream(s, indent + "  ", v.object_class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detection_score: ";
    Printer<float>::stream(s, indent + "  ", v.detection_score);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xmin: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xmin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "xmax: ";
    Printer<int16_t>::stream(s, indent + "  ", v.xmax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymin: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ymin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ymax: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ymax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance_xmin: ";
    Printer<float>::stream(s, indent + "  ", v.variance_xmin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance_xmax: ";
    Printer<float>::stream(s, indent + "  ", v.variance_xmax);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance_ymin: ";
    Printer<float>::stream(s, indent + "  ", v.variance_ymin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "variance_ymax: ";
    Printer<float>::stream(s, indent + "  ", v.variance_ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEURAL_NETWORK_MSGS_MESSAGE_NEURALNETWORKDETECTION_H
