// Generated by gencpp from file neural_network_detector/NeuralNetworkDetectionArray.msg
// DO NOT EDIT!


#ifndef NEURAL_NETWORK_DETECTOR_MESSAGE_NEURALNETWORKDETECTIONARRAY_H
#define NEURAL_NETWORK_DETECTOR_MESSAGE_NEURALNETWORKDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <neural_network_detector/NeuralNetworkDetection.h>

namespace neural_network_detector
{
template <class ContainerAllocator>
struct NeuralNetworkDetectionArray_
{
  typedef NeuralNetworkDetectionArray_<ContainerAllocator> Type;

  NeuralNetworkDetectionArray_()
    : header()
    , detections()  {
    }
  NeuralNetworkDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::neural_network_detector::NeuralNetworkDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::neural_network_detector::NeuralNetworkDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct NeuralNetworkDetectionArray_

typedef ::neural_network_detector::NeuralNetworkDetectionArray_<std::allocator<void> > NeuralNetworkDetectionArray;

typedef boost::shared_ptr< ::neural_network_detector::NeuralNetworkDetectionArray > NeuralNetworkDetectionArrayPtr;
typedef boost::shared_ptr< ::neural_network_detector::NeuralNetworkDetectionArray const> NeuralNetworkDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator1> & lhs, const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator1> & lhs, const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace neural_network_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62804b61e09b797611b00ce77fd7ac20";
  }

  static const char* value(const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62804b61e09b7976ULL;
  static const uint64_t static_value2 = 0x11b00ce77fd7ac20ULL;
};

template<class ContainerAllocator>
struct DataType< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neural_network_detector/NeuralNetworkDetectionArray";
  }

  static const char* value(const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"NeuralNetworkDetection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: neural_network_detector/NeuralNetworkDetection\n"
"Header header\n"
"\n"
"int16 object_class\n"
"float32 detection_score\n"
"\n"
"int16 xmin\n"
"int16 xmax\n"
"int16 ymin\n"
"int16 ymax\n"
"\n"
"float32 variance_xmin\n"
"float32 variance_xmax\n"
"float32 variance_ymin\n"
"float32 variance_ymax\n"
;
  }

  static const char* value(const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeuralNetworkDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neural_network_detector::NeuralNetworkDetectionArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detections: ";
    if (v.detections.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::neural_network_detector::NeuralNetworkDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.detections[i]);
    }
    if (v.detections.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEURAL_NETWORK_DETECTOR_MESSAGE_NEURALNETWORKDETECTIONARRAY_H
