//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the target_tracker_distributed_kf package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __target_tracker_distributed_kf__KALMANFILTERPARAMSCONFIG_H__
#define __target_tracker_distributed_kf__KALMANFILTERPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace target_tracker_distributed_kf
{
  class KalmanFilterParamsConfigStatics;

  class KalmanFilterParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(KalmanFilterParamsConfig &config, const KalmanFilterParamsConfig &max, const KalmanFilterParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const KalmanFilterParamsConfig &config1, const KalmanFilterParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, KalmanFilterParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const KalmanFilterParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, KalmanFilterParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const KalmanFilterParamsConfig &config) const = 0;
      virtual void getValue(const KalmanFilterParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T KalmanFilterParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T KalmanFilterParamsConfig::* field;

      virtual void clamp(KalmanFilterParamsConfig &config, const KalmanFilterParamsConfig &max, const KalmanFilterParamsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const KalmanFilterParamsConfig &config1, const KalmanFilterParamsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, KalmanFilterParamsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const KalmanFilterParamsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, KalmanFilterParamsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const KalmanFilterParamsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const KalmanFilterParamsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, KalmanFilterParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, KalmanFilterParamsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<KalmanFilterParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(KalmanFilterParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("posGlobalOffsetBiasX"==(*_i)->name){posGlobalOffsetBiasX = boost::any_cast<double>(val);}
        if("posGlobalOffsetBiasY"==(*_i)->name){posGlobalOffsetBiasY = boost::any_cast<double>(val);}
        if("posGlobalOffsetBiasZ"==(*_i)->name){posGlobalOffsetBiasZ = boost::any_cast<double>(val);}
        if("noisePosXVar"==(*_i)->name){noisePosXVar = boost::any_cast<double>(val);}
        if("noisePosYVar"==(*_i)->name){noisePosYVar = boost::any_cast<double>(val);}
        if("noisePosZVar"==(*_i)->name){noisePosZVar = boost::any_cast<double>(val);}
        if("noiseVelXVar"==(*_i)->name){noiseVelXVar = boost::any_cast<double>(val);}
        if("noiseVelYVar"==(*_i)->name){noiseVelYVar = boost::any_cast<double>(val);}
        if("noiseVelZVar"==(*_i)->name){noiseVelZVar = boost::any_cast<double>(val);}
        if("noiseOffXVar"==(*_i)->name){noiseOffXVar = boost::any_cast<double>(val);}
        if("noiseOffYVar"==(*_i)->name){noiseOffYVar = boost::any_cast<double>(val);}
        if("noiseOffZVar"==(*_i)->name){noiseOffZVar = boost::any_cast<double>(val);}
        if("velocityDecayTime"==(*_i)->name){velocityDecayTime = boost::any_cast<double>(val);}
        if("offsetDecayTime"==(*_i)->name){offsetDecayTime = boost::any_cast<double>(val);}
        if("falsePositiveThresholdSigma"==(*_i)->name){falsePositiveThresholdSigma = boost::any_cast<double>(val);}
      }
    }

    double posGlobalOffsetBiasX;
double posGlobalOffsetBiasY;
double posGlobalOffsetBiasZ;
double noisePosXVar;
double noisePosYVar;
double noisePosZVar;
double noiseVelXVar;
double noiseVelYVar;
double noiseVelZVar;
double noiseOffXVar;
double noiseOffYVar;
double noiseOffZVar;
double velocityDecayTime;
double offsetDecayTime;
double falsePositiveThresholdSigma;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double posGlobalOffsetBiasX;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double posGlobalOffsetBiasY;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double posGlobalOffsetBiasZ;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noisePosXVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noisePosYVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noisePosZVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseVelXVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseVelYVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseVelZVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseOffXVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseOffYVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double noiseOffZVar;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double velocityDecayTime;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double offsetDecayTime;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double falsePositiveThresholdSigma;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("KalmanFilterParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const KalmanFilterParamsConfig &__max__ = __getMax__();
      const KalmanFilterParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const KalmanFilterParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const KalmanFilterParamsConfig &__getDefault__();
    static const KalmanFilterParamsConfig &__getMax__();
    static const KalmanFilterParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const KalmanFilterParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void KalmanFilterParamsConfig::ParamDescription<std::string>::clamp(KalmanFilterParamsConfig &config, const KalmanFilterParamsConfig &max, const KalmanFilterParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class KalmanFilterParamsConfigStatics
  {
    friend class KalmanFilterParamsConfig;

    KalmanFilterParamsConfigStatics()
    {
KalmanFilterParamsConfig::GroupDescription<KalmanFilterParamsConfig::DEFAULT, KalmanFilterParamsConfig> Default("Default", "", 0, 0, true, &KalmanFilterParamsConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.posGlobalOffsetBiasX = -25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.posGlobalOffsetBiasX = 25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.posGlobalOffsetBiasX = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasX", "double", 0, "posGlobalOffsetBiasX", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasX)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasX", "double", 0, "posGlobalOffsetBiasX", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasX)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.posGlobalOffsetBiasY = -25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.posGlobalOffsetBiasY = 25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.posGlobalOffsetBiasY = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasY", "double", 0, "posGlobalOffsetBiasY", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasY)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasY", "double", 0, "posGlobalOffsetBiasY", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasY)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.posGlobalOffsetBiasZ = -25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.posGlobalOffsetBiasZ = 25.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.posGlobalOffsetBiasZ = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasZ", "double", 0, "posGlobalOffsetBiasZ", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasZ)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("posGlobalOffsetBiasZ", "double", 0, "posGlobalOffsetBiasZ", "", &KalmanFilterParamsConfig::posGlobalOffsetBiasZ)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noisePosXVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noisePosXVar = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noisePosXVar = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosXVar", "double", 0, "noisePosXVar", "", &KalmanFilterParamsConfig::noisePosXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosXVar", "double", 0, "noisePosXVar", "", &KalmanFilterParamsConfig::noisePosXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noisePosYVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noisePosYVar = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noisePosYVar = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosYVar", "double", 0, "noisePosYVar", "", &KalmanFilterParamsConfig::noisePosYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosYVar", "double", 0, "noisePosYVar", "", &KalmanFilterParamsConfig::noisePosYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noisePosZVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noisePosZVar = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noisePosZVar = 0.4;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosZVar", "double", 0, "noisePosZVar", "", &KalmanFilterParamsConfig::noisePosZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noisePosZVar", "double", 0, "noisePosZVar", "", &KalmanFilterParamsConfig::noisePosZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseVelXVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseVelXVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseVelXVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelXVar", "double", 0, "noiseVelXVar", "", &KalmanFilterParamsConfig::noiseVelXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelXVar", "double", 0, "noiseVelXVar", "", &KalmanFilterParamsConfig::noiseVelXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseVelYVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseVelYVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseVelYVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelYVar", "double", 0, "noiseVelYVar", "", &KalmanFilterParamsConfig::noiseVelYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelYVar", "double", 0, "noiseVelYVar", "", &KalmanFilterParamsConfig::noiseVelYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseVelZVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseVelZVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseVelZVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelZVar", "double", 0, "noiseVelZVar", "", &KalmanFilterParamsConfig::noiseVelZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseVelZVar", "double", 0, "noiseVelZVar", "", &KalmanFilterParamsConfig::noiseVelZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseOffXVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseOffXVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseOffXVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffXVar", "double", 0, "noiseOffXVar", "", &KalmanFilterParamsConfig::noiseOffXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffXVar", "double", 0, "noiseOffXVar", "", &KalmanFilterParamsConfig::noiseOffXVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseOffYVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseOffYVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseOffYVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffYVar", "double", 0, "noiseOffYVar", "", &KalmanFilterParamsConfig::noiseOffYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffYVar", "double", 0, "noiseOffYVar", "", &KalmanFilterParamsConfig::noiseOffYVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.noiseOffZVar = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.noiseOffZVar = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.noiseOffZVar = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffZVar", "double", 0, "noiseOffZVar", "", &KalmanFilterParamsConfig::noiseOffZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("noiseOffZVar", "double", 0, "noiseOffZVar", "", &KalmanFilterParamsConfig::noiseOffZVar)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.velocityDecayTime = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.velocityDecayTime = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.velocityDecayTime = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("velocityDecayTime", "double", 0, "velocityDecayTime", "", &KalmanFilterParamsConfig::velocityDecayTime)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("velocityDecayTime", "double", 0, "velocityDecayTime", "", &KalmanFilterParamsConfig::velocityDecayTime)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.offsetDecayTime = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.offsetDecayTime = 300.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.offsetDecayTime = 30.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("offsetDecayTime", "double", 0, "offsetDecayTime", "", &KalmanFilterParamsConfig::offsetDecayTime)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("offsetDecayTime", "double", 0, "offsetDecayTime", "", &KalmanFilterParamsConfig::offsetDecayTime)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.falsePositiveThresholdSigma = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.falsePositiveThresholdSigma = 50.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.falsePositiveThresholdSigma = 6.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("falsePositiveThresholdSigma", "double", 0, "falsePositiveThresholdSigma", "", &KalmanFilterParamsConfig::falsePositiveThresholdSigma)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr(new KalmanFilterParamsConfig::ParamDescription<double>("falsePositiveThresholdSigma", "double", 0, "falsePositiveThresholdSigma", "", &KalmanFilterParamsConfig::falsePositiveThresholdSigma)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(KalmanFilterParamsConfig::AbstractGroupDescriptionConstPtr(new KalmanFilterParamsConfig::GroupDescription<KalmanFilterParamsConfig::DEFAULT, KalmanFilterParamsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<KalmanFilterParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<KalmanFilterParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    KalmanFilterParamsConfig __max__;
    KalmanFilterParamsConfig __min__;
    KalmanFilterParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const KalmanFilterParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static KalmanFilterParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &KalmanFilterParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const KalmanFilterParamsConfig &KalmanFilterParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const KalmanFilterParamsConfig &KalmanFilterParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const KalmanFilterParamsConfig &KalmanFilterParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<KalmanFilterParamsConfig::AbstractParamDescriptionConstPtr> &KalmanFilterParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<KalmanFilterParamsConfig::AbstractGroupDescriptionConstPtr> &KalmanFilterParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const KalmanFilterParamsConfigStatics *KalmanFilterParamsConfig::__get_statics__()
  {
    const static KalmanFilterParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = KalmanFilterParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __KALMANFILTERPARAMSRECONFIGURATOR_H__
