// Generated by gencpp from file librepilot/gyro_bias.msg
// DO NOT EDIT!


#ifndef LIBREPILOT_MESSAGE_GYRO_BIAS_H
#define LIBREPILOT_MESSAGE_GYRO_BIAS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace librepilot
{
template <class ContainerAllocator>
struct gyro_bias_
{
  typedef gyro_bias_<ContainerAllocator> Type;

  gyro_bias_()
    : header()
    , bias()  {
    }
  gyro_bias_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bias(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _bias_type;
  _bias_type bias;





  typedef boost::shared_ptr< ::librepilot::gyro_bias_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::librepilot::gyro_bias_<ContainerAllocator> const> ConstPtr;

}; // struct gyro_bias_

typedef ::librepilot::gyro_bias_<std::allocator<void> > gyro_bias;

typedef boost::shared_ptr< ::librepilot::gyro_bias > gyro_biasPtr;
typedef boost::shared_ptr< ::librepilot::gyro_bias const> gyro_biasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::librepilot::gyro_bias_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::librepilot::gyro_bias_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::librepilot::gyro_bias_<ContainerAllocator1> & lhs, const ::librepilot::gyro_bias_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bias == rhs.bias;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::librepilot::gyro_bias_<ContainerAllocator1> & lhs, const ::librepilot::gyro_bias_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace librepilot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::librepilot::gyro_bias_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::librepilot::gyro_bias_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::librepilot::gyro_bias_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::librepilot::gyro_bias_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::librepilot::gyro_bias_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::librepilot::gyro_bias_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::librepilot::gyro_bias_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42d5df8dc8f400c341540257a64e8a58";
  }

  static const char* value(const ::librepilot::gyro_bias_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42d5df8dc8f400c3ULL;
  static const uint64_t static_value2 = 0x41540257a64e8a58ULL;
};

template<class ContainerAllocator>
struct DataType< ::librepilot::gyro_bias_<ContainerAllocator> >
{
  static const char* value()
  {
    return "librepilot/gyro_bias";
  }

  static const char* value(const ::librepilot::gyro_bias_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::librepilot::gyro_bias_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A representation of Gyroscope bias in body frame (x,y,z)\n"
"\n"
"Header header\n"
"geometry_msgs/Vector3 bias\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::librepilot::gyro_bias_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::librepilot::gyro_bias_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bias);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gyro_bias_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::librepilot::gyro_bias_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::librepilot::gyro_bias_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bias: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.bias);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIBREPILOT_MESSAGE_GYRO_BIAS_H
