# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from neural_network_msgs/NeuralNetworkDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class NeuralNetworkDetection(genpy.Message):
  _md5sum = "32bfad3528ed00c65e8e80188ba162ac"
  _type = "neural_network_msgs/NeuralNetworkDetection"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

int16 object_class
float32 detection_score

int16 xmin
int16 xmax
int16 ymin
int16 ymax

float32 variance_xmin
float32 variance_xmax
float32 variance_ymin
float32 variance_ymax
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','object_class','detection_score','xmin','xmax','ymin','ymax','variance_xmin','variance_xmax','variance_ymin','variance_ymax']
  _slot_types = ['std_msgs/Header','int16','float32','int16','int16','int16','int16','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,object_class,detection_score,xmin,xmax,ymin,ymax,variance_xmin,variance_xmax,variance_ymin,variance_ymax

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NeuralNetworkDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object_class is None:
        self.object_class = 0
      if self.detection_score is None:
        self.detection_score = 0.
      if self.xmin is None:
        self.xmin = 0
      if self.xmax is None:
        self.xmax = 0
      if self.ymin is None:
        self.ymin = 0
      if self.ymax is None:
        self.ymax = 0
      if self.variance_xmin is None:
        self.variance_xmin = 0.
      if self.variance_xmax is None:
        self.variance_xmax = 0.
      if self.variance_ymin is None:
        self.variance_ymin = 0.
      if self.variance_ymax is None:
        self.variance_ymax = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.object_class = 0
      self.detection_score = 0.
      self.xmin = 0
      self.xmax = 0
      self.ymin = 0
      self.ymax = 0
      self.variance_xmin = 0.
      self.variance_xmax = 0.
      self.variance_ymin = 0.
      self.variance_ymax = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hf4h4f().pack(_x.object_class, _x.detection_score, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.variance_xmin, _x.variance_xmax, _x.variance_ymin, _x.variance_ymax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.object_class, _x.detection_score, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.variance_xmin, _x.variance_xmax, _x.variance_ymin, _x.variance_ymax,) = _get_struct_hf4h4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_hf4h4f().pack(_x.object_class, _x.detection_score, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.variance_xmin, _x.variance_xmax, _x.variance_ymin, _x.variance_ymax))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.object_class, _x.detection_score, _x.xmin, _x.xmax, _x.ymin, _x.ymax, _x.variance_xmin, _x.variance_xmax, _x.variance_ymin, _x.variance_ymax,) = _get_struct_hf4h4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_hf4h4f = None
def _get_struct_hf4h4f():
    global _struct_hf4h4f
    if _struct_hf4h4f is None:
        _struct_hf4h4f = struct.Struct("<hf4h4f")
    return _struct_hf4h4f
