# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from neural_network_detector/NeuralNetworkFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class NeuralNetworkFeedback(genpy.Message):
  _md5sum = "7cbb8a63be188eb83ce5036283cdca4b"
  _type = "neural_network_detector/NeuralNetworkFeedback"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int16 ymin
int16 ymax
int16 xcenter

#Debug stuff
bool debug_included
int16 head_raw
int16 feet_raw
int16 ycenter
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ymin','ymax','xcenter','debug_included','head_raw','feet_raw','ycenter']
  _slot_types = ['std_msgs/Header','int16','int16','int16','bool','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ymin,ymax,xcenter,debug_included,head_raw,feet_raw,ycenter

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NeuralNetworkFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ymin is None:
        self.ymin = 0
      if self.ymax is None:
        self.ymax = 0
      if self.xcenter is None:
        self.xcenter = 0
      if self.debug_included is None:
        self.debug_included = False
      if self.head_raw is None:
        self.head_raw = 0
      if self.feet_raw is None:
        self.feet_raw = 0
      if self.ycenter is None:
        self.ycenter = 0
    else:
      self.header = std_msgs.msg.Header()
      self.ymin = 0
      self.ymax = 0
      self.xcenter = 0
      self.debug_included = False
      self.head_raw = 0
      self.feet_raw = 0
      self.ycenter = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3hB3h().pack(_x.ymin, _x.ymax, _x.xcenter, _x.debug_included, _x.head_raw, _x.feet_raw, _x.ycenter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.ymin, _x.ymax, _x.xcenter, _x.debug_included, _x.head_raw, _x.feet_raw, _x.ycenter,) = _get_struct_3hB3h().unpack(str[start:end])
      self.debug_included = bool(self.debug_included)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3hB3h().pack(_x.ymin, _x.ymax, _x.xcenter, _x.debug_included, _x.head_raw, _x.feet_raw, _x.ycenter))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.ymin, _x.ymax, _x.xcenter, _x.debug_included, _x.head_raw, _x.feet_raw, _x.ycenter,) = _get_struct_3hB3h().unpack(str[start:end])
      self.debug_included = bool(self.debug_included)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3hB3h = None
def _get_struct_3hB3h():
    global _struct_3hB3h
    if _struct_3hB3h is None:
        _struct_3hB3h = struct.Struct("<3hB3h")
    return _struct_3hB3h
