(cl:defpackage neural_network_msgs-msg
  (:use )
  (:export
   "<NEURALNETWORKDETECTION>"
   "NEURALNETWORKDETECTION"
   "<NEURALNETWORKDETECTION>"
   "NEURALNETWORKDETECTION"
   "<NEURALNETWORKDETECTIONARRAY>"
   "NEURALNETWORKDETECTIONARRAY"
   "<NEURALNETWORKDETECTIONARRAY>"
   "NEURALNETWORKDETECTIONARRAY"
   "<NEURALNETWORKFEEDBACK>"
   "NEURALNETWORKFEEDBACK"
   "<NEURALNETWORKFEEDBACK>"
   "NEURALNETWORKFEEDBACK"
   "<NEURALNETWORKNUMBEROFDETECTIONS>"
   "NEURALNETWORKNUMBEROFDETECTIONS"
   "<NEURALNETWORKNUMBEROFDETECTIONS>"
   "NEURALNETWORKNUMBEROFDETECTIONS"
  ))

