# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from librepilot/TransmitterInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class TransmitterInfo(genpy.Message):
  _md5sum = "157af9dabf4ea5c891d7a24aed868284"
  _type = "librepilot/TransmitterInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
int32 ROSControlled
int32 Armed
int32 FlightModeSwitch
float64 Roll
float64 Pitch
float64 Yaw
float64 Thrust
float64 Collective
float64 Throttle
float64[4] Accessory

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ROSControlled','Armed','FlightModeSwitch','Roll','Pitch','Yaw','Thrust','Collective','Throttle','Accessory']
  _slot_types = ['std_msgs/Header','int32','int32','int32','float64','float64','float64','float64','float64','float64','float64[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ROSControlled,Armed,FlightModeSwitch,Roll,Pitch,Yaw,Thrust,Collective,Throttle,Accessory

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TransmitterInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ROSControlled is None:
        self.ROSControlled = 0
      if self.Armed is None:
        self.Armed = 0
      if self.FlightModeSwitch is None:
        self.FlightModeSwitch = 0
      if self.Roll is None:
        self.Roll = 0.
      if self.Pitch is None:
        self.Pitch = 0.
      if self.Yaw is None:
        self.Yaw = 0.
      if self.Thrust is None:
        self.Thrust = 0.
      if self.Collective is None:
        self.Collective = 0.
      if self.Throttle is None:
        self.Throttle = 0.
      if self.Accessory is None:
        self.Accessory = [0.] * 4
    else:
      self.header = std_msgs.msg.Header()
      self.ROSControlled = 0
      self.Armed = 0
      self.FlightModeSwitch = 0
      self.Roll = 0.
      self.Pitch = 0.
      self.Yaw = 0.
      self.Thrust = 0.
      self.Collective = 0.
      self.Throttle = 0.
      self.Accessory = [0.] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i6d().pack(_x.ROSControlled, _x.Armed, _x.FlightModeSwitch, _x.Roll, _x.Pitch, _x.Yaw, _x.Thrust, _x.Collective, _x.Throttle))
      buff.write(_get_struct_4d().pack(*self.Accessory))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.ROSControlled, _x.Armed, _x.FlightModeSwitch, _x.Roll, _x.Pitch, _x.Yaw, _x.Thrust, _x.Collective, _x.Throttle,) = _get_struct_3i6d().unpack(str[start:end])
      start = end
      end += 32
      self.Accessory = _get_struct_4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3i6d().pack(_x.ROSControlled, _x.Armed, _x.FlightModeSwitch, _x.Roll, _x.Pitch, _x.Yaw, _x.Thrust, _x.Collective, _x.Throttle))
      buff.write(self.Accessory.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 60
      (_x.ROSControlled, _x.Armed, _x.FlightModeSwitch, _x.Roll, _x.Pitch, _x.Yaw, _x.Thrust, _x.Collective, _x.Throttle,) = _get_struct_3i6d().unpack(str[start:end])
      start = end
      end += 32
      self.Accessory = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3i6d = None
def _get_struct_3i6d():
    global _struct_3i6d
    if _struct_3i6d is None:
        _struct_3i6d = struct.Struct("<3i6d")
    return _struct_3i6d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
