(cl:in-package librepilot-msg)
(cl:export '(HEADER-VAL
          HEADER
          STATUS-VAL
          STATUS
          FRACTIONAL_PROGRESS-VAL
          FRACTIONAL_PROGRESS
          ERROR-VAL
          ERROR
          PATHDIRECTION-VAL
          PATHDIRECTION
          PATHCORRECTION-VAL
          PATHCORRECTION
          PATHTIME-VAL
          PATHTIME
          MODE-VAL
          MODE
          MODEPARAMETERS-VAL
          MODEPARAMETERS
          START-VAL
          START
          END-VAL
          END
          STARTINGVELOCITY-VAL
          STARTINGVELOCITY
          ENDINGVELOCITY-VAL
          ENDINGVELOCITY
          VELOCITYDESIRED-VAL
          VELOCITYDESIRED
))