//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the nmpc_planner package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __nmpc_planner__NMPCPLANNERPARAMSCONFIG_H__
#define __nmpc_planner__NMPCPLANNERPARAMSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace nmpc_planner
{
  class nmpcPlannerParamsConfigStatics;

  class nmpcPlannerParamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(nmpcPlannerParamsConfig &config, const nmpcPlannerParamsConfig &max, const nmpcPlannerParamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const nmpcPlannerParamsConfig &config1, const nmpcPlannerParamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, nmpcPlannerParamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const nmpcPlannerParamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, nmpcPlannerParamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const nmpcPlannerParamsConfig &config) const = 0;
      virtual void getValue(const nmpcPlannerParamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T nmpcPlannerParamsConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T nmpcPlannerParamsConfig::* field;

      virtual void clamp(nmpcPlannerParamsConfig &config, const nmpcPlannerParamsConfig &max, const nmpcPlannerParamsConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const nmpcPlannerParamsConfig &config1, const nmpcPlannerParamsConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, nmpcPlannerParamsConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const nmpcPlannerParamsConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, nmpcPlannerParamsConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const nmpcPlannerParamsConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const nmpcPlannerParamsConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, nmpcPlannerParamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, nmpcPlannerParamsConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<nmpcPlannerParamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(nmpcPlannerParamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("neighborDistThreshold"==(*_i)->name){neighborDistThreshold = boost::any_cast<double>(val);}
        if("approachAngleThreshold"==(*_i)->name){approachAngleThreshold = boost::any_cast<double>(val);}
        if("distanceThresholdToTarget"==(*_i)->name){distanceThresholdToTarget = boost::any_cast<double>(val);}
        if("copterDesiredHeightinNED"==(*_i)->name){copterDesiredHeightinNED = boost::any_cast<double>(val);}
        if("maxOffsetUncertaintyRadius"==(*_i)->name){maxOffsetUncertaintyRadius = boost::any_cast<double>(val);}
        if("targetGuaranteeThreshold"==(*_i)->name){targetGuaranteeThreshold = boost::any_cast<double>(val);}
        if("activeGuaranteeThreshold"==(*_i)->name){activeGuaranteeThreshold = boost::any_cast<double>(val);}
        if("obstacleGuaranteeThreshold"==(*_i)->name){obstacleGuaranteeThreshold = boost::any_cast<double>(val);}
        if("neighborGuaranteeThreshold"==(*_i)->name){neighborGuaranteeThreshold = boost::any_cast<double>(val);}
        if("INTERNAL_SUB_STEP"==(*_i)->name){INTERNAL_SUB_STEP = boost::any_cast<double>(val);}
        if("deltaT"==(*_i)->name){deltaT = boost::any_cast<double>(val);}
        if("activeTrackingWeight"==(*_i)->name){activeTrackingWeight = boost::any_cast<double>(val);}
        if("energyWeight"==(*_i)->name){energyWeight = boost::any_cast<double>(val);}
        if("copterVelocityLimitHorizontal"==(*_i)->name){copterVelocityLimitHorizontal = boost::any_cast<double>(val);}
        if("copterVelocityLimitVertical"==(*_i)->name){copterVelocityLimitVertical = boost::any_cast<double>(val);}
        if("copterAccelarationLimitHorizontal"==(*_i)->name){copterAccelarationLimitHorizontal = boost::any_cast<double>(val);}
        if("copterAccelarationLimitVertical"==(*_i)->name){copterAccelarationLimitVertical = boost::any_cast<double>(val);}
      }
    }

    double neighborDistThreshold;
double approachAngleThreshold;
double distanceThresholdToTarget;
double copterDesiredHeightinNED;
double maxOffsetUncertaintyRadius;
double targetGuaranteeThreshold;
double activeGuaranteeThreshold;
double obstacleGuaranteeThreshold;
double neighborGuaranteeThreshold;
double INTERNAL_SUB_STEP;
double deltaT;
double activeTrackingWeight;
double energyWeight;
double copterVelocityLimitHorizontal;
double copterVelocityLimitVertical;
double copterAccelarationLimitHorizontal;
double copterAccelarationLimitVertical;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double neighborDistThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double approachAngleThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double distanceThresholdToTarget;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double copterDesiredHeightinNED;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double maxOffsetUncertaintyRadius;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double targetGuaranteeThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double activeGuaranteeThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double obstacleGuaranteeThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double neighborGuaranteeThreshold;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double INTERNAL_SUB_STEP;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double deltaT;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double activeTrackingWeight;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double energyWeight;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double copterVelocityLimitHorizontal;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double copterVelocityLimitVertical;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double copterAccelarationLimitHorizontal;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double copterAccelarationLimitVertical;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("nmpcPlannerParamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const nmpcPlannerParamsConfig &__max__ = __getMax__();
      const nmpcPlannerParamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const nmpcPlannerParamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const nmpcPlannerParamsConfig &__getDefault__();
    static const nmpcPlannerParamsConfig &__getMax__();
    static const nmpcPlannerParamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const nmpcPlannerParamsConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void nmpcPlannerParamsConfig::ParamDescription<std::string>::clamp(nmpcPlannerParamsConfig &config, const nmpcPlannerParamsConfig &max, const nmpcPlannerParamsConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class nmpcPlannerParamsConfigStatics
  {
    friend class nmpcPlannerParamsConfig;

    nmpcPlannerParamsConfigStatics()
    {
nmpcPlannerParamsConfig::GroupDescription<nmpcPlannerParamsConfig::DEFAULT, nmpcPlannerParamsConfig> Default("Default", "", 0, 0, true, &nmpcPlannerParamsConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.neighborDistThreshold = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.neighborDistThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.neighborDistThreshold = 7.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("neighborDistThreshold", "double", 0, "neighborDistThreshold", "", &nmpcPlannerParamsConfig::neighborDistThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("neighborDistThreshold", "double", 0, "neighborDistThreshold", "", &nmpcPlannerParamsConfig::neighborDistThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.approachAngleThreshold = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.approachAngleThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.approachAngleThreshold = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("approachAngleThreshold", "double", 0, "approachAngleThreshold", "", &nmpcPlannerParamsConfig::approachAngleThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("approachAngleThreshold", "double", 0, "approachAngleThreshold", "", &nmpcPlannerParamsConfig::approachAngleThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.distanceThresholdToTarget = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.distanceThresholdToTarget = 15.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.distanceThresholdToTarget = 8.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("distanceThresholdToTarget", "double", 0, "distanceThresholdToTarget", "", &nmpcPlannerParamsConfig::distanceThresholdToTarget)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("distanceThresholdToTarget", "double", 0, "distanceThresholdToTarget", "", &nmpcPlannerParamsConfig::distanceThresholdToTarget)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.copterDesiredHeightinNED = -20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.copterDesiredHeightinNED = -2.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.copterDesiredHeightinNED = -8.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterDesiredHeightinNED", "double", 0, "copterDesiredHeightinNED", "", &nmpcPlannerParamsConfig::copterDesiredHeightinNED)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterDesiredHeightinNED", "double", 0, "copterDesiredHeightinNED", "", &nmpcPlannerParamsConfig::copterDesiredHeightinNED)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.maxOffsetUncertaintyRadius = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.maxOffsetUncertaintyRadius = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.maxOffsetUncertaintyRadius = 3.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("maxOffsetUncertaintyRadius", "double", 0, "maxOffsetUncertaintyRadius", "", &nmpcPlannerParamsConfig::maxOffsetUncertaintyRadius)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("maxOffsetUncertaintyRadius", "double", 0, "maxOffsetUncertaintyRadius", "", &nmpcPlannerParamsConfig::maxOffsetUncertaintyRadius)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.targetGuaranteeThreshold = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.targetGuaranteeThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.targetGuaranteeThreshold = 7.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("targetGuaranteeThreshold", "double", 0, "targetGuaranteeThreshold", "", &nmpcPlannerParamsConfig::targetGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("targetGuaranteeThreshold", "double", 0, "targetGuaranteeThreshold", "", &nmpcPlannerParamsConfig::targetGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.activeGuaranteeThreshold = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.activeGuaranteeThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.activeGuaranteeThreshold = 1.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("activeGuaranteeThreshold", "double", 0, "activeGuaranteeThreshold", "", &nmpcPlannerParamsConfig::activeGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("activeGuaranteeThreshold", "double", 0, "activeGuaranteeThreshold", "", &nmpcPlannerParamsConfig::activeGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.obstacleGuaranteeThreshold = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.obstacleGuaranteeThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.obstacleGuaranteeThreshold = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("obstacleGuaranteeThreshold", "double", 0, "obstacleGuaranteeThreshold", "", &nmpcPlannerParamsConfig::obstacleGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("obstacleGuaranteeThreshold", "double", 0, "obstacleGuaranteeThreshold", "", &nmpcPlannerParamsConfig::obstacleGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.neighborGuaranteeThreshold = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.neighborGuaranteeThreshold = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.neighborGuaranteeThreshold = 1.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("neighborGuaranteeThreshold", "double", 0, "neighborGuaranteeThreshold", "", &nmpcPlannerParamsConfig::neighborGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("neighborGuaranteeThreshold", "double", 0, "neighborGuaranteeThreshold", "", &nmpcPlannerParamsConfig::neighborGuaranteeThreshold)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.INTERNAL_SUB_STEP = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.INTERNAL_SUB_STEP = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.INTERNAL_SUB_STEP = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("INTERNAL_SUB_STEP", "double", 0, "INTERNAL_SUB_STEP", "", &nmpcPlannerParamsConfig::INTERNAL_SUB_STEP)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("INTERNAL_SUB_STEP", "double", 0, "INTERNAL_SUB_STEP", "", &nmpcPlannerParamsConfig::INTERNAL_SUB_STEP)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.deltaT = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.deltaT = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.deltaT = 0.1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("deltaT", "double", 0, "deltaT", "", &nmpcPlannerParamsConfig::deltaT)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("deltaT", "double", 0, "deltaT", "", &nmpcPlannerParamsConfig::deltaT)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.activeTrackingWeight = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.activeTrackingWeight = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.activeTrackingWeight = 100.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("activeTrackingWeight", "double", 0, "activeTrackingWeight", "", &nmpcPlannerParamsConfig::activeTrackingWeight)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("activeTrackingWeight", "double", 0, "activeTrackingWeight", "", &nmpcPlannerParamsConfig::activeTrackingWeight)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.energyWeight = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.energyWeight = 1000.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.energyWeight = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("energyWeight", "double", 0, "energyWeight", "", &nmpcPlannerParamsConfig::energyWeight)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("energyWeight", "double", 0, "energyWeight", "", &nmpcPlannerParamsConfig::energyWeight)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.copterVelocityLimitHorizontal = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.copterVelocityLimitHorizontal = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.copterVelocityLimitHorizontal = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterVelocityLimitHorizontal", "double", 0, "copterVelocityLimitHorizontal", "", &nmpcPlannerParamsConfig::copterVelocityLimitHorizontal)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterVelocityLimitHorizontal", "double", 0, "copterVelocityLimitHorizontal", "", &nmpcPlannerParamsConfig::copterVelocityLimitHorizontal)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.copterVelocityLimitVertical = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.copterVelocityLimitVertical = 10.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.copterVelocityLimitVertical = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterVelocityLimitVertical", "double", 0, "copterVelocityLimitVertical", "", &nmpcPlannerParamsConfig::copterVelocityLimitVertical)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterVelocityLimitVertical", "double", 0, "copterVelocityLimitVertical", "", &nmpcPlannerParamsConfig::copterVelocityLimitVertical)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.copterAccelarationLimitHorizontal = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.copterAccelarationLimitHorizontal = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.copterAccelarationLimitHorizontal = 5.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterAccelarationLimitHorizontal", "double", 0, "copterAccelarationLimitHorizontal", "", &nmpcPlannerParamsConfig::copterAccelarationLimitHorizontal)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterAccelarationLimitHorizontal", "double", 0, "copterAccelarationLimitHorizontal", "", &nmpcPlannerParamsConfig::copterAccelarationLimitHorizontal)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.copterAccelarationLimitVertical = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.copterAccelarationLimitVertical = 20.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.copterAccelarationLimitVertical = 11.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterAccelarationLimitVertical", "double", 0, "copterAccelarationLimitVertical", "", &nmpcPlannerParamsConfig::copterAccelarationLimitVertical)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr(new nmpcPlannerParamsConfig::ParamDescription<double>("copterAccelarationLimitVertical", "double", 0, "copterAccelarationLimitVertical", "", &nmpcPlannerParamsConfig::copterAccelarationLimitVertical)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(nmpcPlannerParamsConfig::AbstractGroupDescriptionConstPtr(new nmpcPlannerParamsConfig::GroupDescription<nmpcPlannerParamsConfig::DEFAULT, nmpcPlannerParamsConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<nmpcPlannerParamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<nmpcPlannerParamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    nmpcPlannerParamsConfig __max__;
    nmpcPlannerParamsConfig __min__;
    nmpcPlannerParamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const nmpcPlannerParamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static nmpcPlannerParamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &nmpcPlannerParamsConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const nmpcPlannerParamsConfig &nmpcPlannerParamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const nmpcPlannerParamsConfig &nmpcPlannerParamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const nmpcPlannerParamsConfig &nmpcPlannerParamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<nmpcPlannerParamsConfig::AbstractParamDescriptionConstPtr> &nmpcPlannerParamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<nmpcPlannerParamsConfig::AbstractGroupDescriptionConstPtr> &nmpcPlannerParamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const nmpcPlannerParamsConfigStatics *nmpcPlannerParamsConfig::__get_statics__()
  {
    const static nmpcPlannerParamsConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = nmpcPlannerParamsConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __NMPCPLANNERPARAMSRECONFIGURATOR_H__
